export const studentMockData=[
    {
        year:2021,
        month:"Jan",
        name: "Buy a car",
        price: 100,
        id:1,
        msv:111,
    },
    {
        year:2021,
        month:"Feb",
        name: "Go to market",
        price: 10,
        id:1,
        msv:112,
    },
    {
        year:2021,
        month:"Mar",
        name: "Pay out school fee",
        price: 20,
        id:1,
        msv:113,
    },
    {
        year:2022,
        month:"Apr",
        name: "Camp",
        price: 50,
        id:2,
        msv:114,
    },
    {
        year:2022,
        month:" May",
        name: "Eat and drink",
        price: 0,
        id:2,
        msv:115,
    },
    {
        year:2022,
        month:" Jun",
        name: "buy clothes",
        price: 30,
        id:2,
        msv:116,
    },
    {
        year:2023,
        month:"July",
        name: "buy clothes",
        price: 70,
        id:3,
        msv:117,
    },
    {
        year:2023,
        month:"Aug",
        name: "Play football",
        price: 40,
        id:3,
        msv:118,
    },
    {
        year:2023,
        month:"Sep",
        name: "Buy house",
        price: 80,
        id:3,
        msv:119,
    },
    {
        year:2024,
        month:"Oct",
        name: "Buy ice cream",
        price: 90,
        id:4,
        msv:120,
    },
    {
        year:2024,
        month:"Nov",
        name: "Free food",
        price: 0,
        id:4,
        msv:121,
    },
    {
        year:2024,
        month:"Dec",
        name: "Buy fan",
        price: 30,
        id:4,
        msv:122,
    },

];